### ISSUE TITLE
Don't compatible with Rails 4

### ISSUE THREAD

**Issue by bastengao** [namick/obfuscate_id#28]
when bundle log this

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    obfuscate_id (>= 0) ruby depends on
      rails (~> 3.2.1) ruby

    rails (4.1.7)
```

**Comment by ACPK** [comment]
gem "obfuscate_id", github: 'ziyadbasheer/obfuscate_id' gives me out of range ID

**Comment by namick** [comment]
This is fixed in the new releases.

**Comment by ACPK** [comment]
@namick Still getting the error below even though I'm using v0.2.0.

    Couldn't find Device with an out of range value for 'id'

**Comment by superacidjax** [comment]
@namick @ACPK me as well, the out of range error. Is there a way to shorten the generated id?

**Comment by ACPK** [comment]
@namick @superacidjax  Why is this still closed?

**Comment by ACPK** [comment]
@namick Did you get it working yet?

**Comment by richardvenneman** [comment]
I can confirm master doesn't work with Rails 4.2.

@superacidjax @ACPK What I see from a quick glance is that obfuscate_id relies on https://github.com/namick/ScatterSwap, which doesn't allow configuring the length or range: https://github.com/namick/scatter_swap/blob/master/lib/scatter_swap/hasher.rb.

**Comment by ACPK** [comment]
@richardvenneman - Thanks for looking into what the issue was. Around this exact day (March 24th) yesterday, @planas made a push request (status:unmerged) to ScatterSwap that adds support for specifying the output length. I'll test and see we can get it work.

**Comment by ACPK** [comment]
@richardvenneman @superacidjax Any progress on getting it to work with a Rails 4.2 application?

**Comment by richardvenneman** [comment]
Did not get it to work, unfortunately.

**Comment by ACPK** [comment]
@richardvenneman -  FYI, just saw that the gem works now as long as you don't give a custom key.

**Comment by ACPK** [comment]
@richardvenneman Any alternatives to this gem for Rails 4.2 and why is this issue closed?

**Comment by richardvenneman** [comment]
@ACPK I wouldn't know, will look for alternatives soon. This issue https://github.com/namick/obfuscate_id/issues/36 also keeps me from trying to run this in production.

**Comment by deneuxa** [comment]
Same problem here => rails 4.2

"Couldn't find X with an out of range value for 'id'"

**Comment by deneuxa** [comment]
any news @bastengao

**Comment by karuppasamy** [comment]
+1 same problem. any updates?

**Comment by elsurudo** [comment]
+1, having the same issue

**Comment by Ericzhiluo** [comment]
+1 same issue with PG
